export const ErrorSeverity = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL',
};

export const ErrorCatalog = {
  TOKEN_VERSION_MISMATCH: {
    code: 'TOKEN_VERSION_MISMATCH',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'TOKEN_VERSION_MISMATCH',
    suggestedAction: 'LOGOUT_FORCE',
  },
  PASSWORD_CHANGED: {
    code: 'PASSWORD_CHANGED',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'PASSWORD_CHANGED',
    suggestedAction: 'LOGOUT_FORCE',
  },
  TOKEN_EXPIRED: {
    code: 'TOKEN_EXPIRED',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'TOKEN_EXPIRED',
    suggestedAction: 'LOGOUT_FORCE',
  },
  INVALID_TOKEN: {
    code: 'INVALID_TOKEN',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'INVALID_TOKEN',
    suggestedAction: 'LOGOUT_FORCE',
  },
  REFRESH_TOKEN_REQUIRED: {
    code: 'REFRESH_TOKEN_REQUIRED',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'REFRESH_TOKEN_REQUIRED',
    suggestedAction: 'LOGOUT_FORCE',
  },
  INVALID_REFRESH_TOKEN: {
    code: 'INVALID_REFRESH_TOKEN',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'INVALID_REFRESH_TOKEN',
    suggestedAction: 'LOGOUT_FORCE',
  },
  REFRESH_TOKEN_REUSE: {
    code: 'REFRESH_TOKEN_REUSE',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'REFRESH_TOKEN_REUSE',
    suggestedAction: 'LOGOUT_FORCE',
  },
  USER_INACTIVE: {
    code: 'USER_INACTIVE',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'USER_INACTIVE',
    suggestedAction: 'LOGOUT_FORCE',
  },
  FORBIDDEN: {
    code: 'FORBIDDEN',
    httpStatus: 403,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'FORBIDDEN',
    suggestedAction: 'GO_BACK',
  },
  UNAUTHORIZED: {
    code: 'UNAUTHORIZED',
    httpStatus: 401,
    severity: ErrorSeverity.CRITICAL,
    retryable: false,
    translationKey: 'UNAUTHORIZED',
    suggestedAction: 'REDIRECT_LOGIN',
  },
  VALIDATION_ERROR: {
    code: 'VALIDATION_ERROR',
    httpStatus: 400,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'VALIDATION_ERROR',
    suggestedAction: 'INLINE_FIELDS',
  },
  EMAIL_ALREADY_EXISTS: {
    code: 'EMAIL_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'EMAIL_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  PHONE_ALREADY_EXISTS: {
    code: 'PHONE_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'PHONE_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  USERNAME_ALREADY_EXISTS: {
    code: 'USERNAME_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'USERNAME_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  NATIONAL_ID_ALREADY_EXISTS: {
    code: 'NATIONAL_ID_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'NATIONAL_ID_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  TEACHER_CODE_ALREADY_EXISTS: {
    code: 'TEACHER_CODE_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'TEACHER_CODE_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  TEACHER_ID_ALREADY_EXISTS: {
    code: 'TEACHER_ID_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'TEACHER_ID_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  STUDENT_CODE_ALREADY_EXISTS: {
    code: 'STUDENT_CODE_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'STUDENT_CODE_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  STUDENT_ID_ALREADY_EXISTS: {
    code: 'STUDENT_ID_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'STUDENT_ID_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  REGISTRATION_NUMBER_ALREADY_EXISTS: {
    code: 'REGISTRATION_NUMBER_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'REGISTRATION_NUMBER_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  EMPLOYEE_CODE_ALREADY_EXISTS: {
    code: 'EMPLOYEE_CODE_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'EMPLOYEE_CODE_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  INVOICE_NUMBER_ALREADY_EXISTS: {
    code: 'INVOICE_NUMBER_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'INVOICE_NUMBER_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  RECEIPT_NUMBER_ALREADY_EXISTS: {
    code: 'RECEIPT_NUMBER_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'RECEIPT_NUMBER_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  PAYMENT_REFERENCE_ALREADY_EXISTS: {
    code: 'PAYMENT_REFERENCE_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'PAYMENT_REFERENCE_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  TRACKING_NUMBER_ALREADY_EXISTS: {
    code: 'TRACKING_NUMBER_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'TRACKING_NUMBER_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  BARCODE_ALREADY_EXISTS: {
    code: 'BARCODE_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'BARCODE_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  SERIAL_NUMBER_ALREADY_EXISTS: {
    code: 'SERIAL_NUMBER_ALREADY_EXISTS',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'SERIAL_NUMBER_ALREADY_EXISTS',
    suggestedAction: 'INLINE_FIELDS',
  },
  DUPLICATE_KEY: {
    code: 'DUPLICATE_KEY',
    httpStatus: 409,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'DUPLICATE_KEY',
    suggestedAction: 'INLINE_FIELDS',
  },
  NOT_FOUND: {
    code: 'NOT_FOUND',
    httpStatus: 404,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'NOT_FOUND',
    suggestedAction: 'RELOAD',
  },
  BUSINESS_RULE_FAILED: {
    code: 'BUSINESS_RULE_FAILED',
    httpStatus: 400,
    severity: ErrorSeverity.WARNING,
    retryable: false,
    translationKey: 'BUSINESS_RULE_FAILED',
    suggestedAction: 'FIX_INPUT',
  },
  DATABASE_ERROR: {
    code: 'DATABASE_ERROR',
    httpStatus: 500,
    severity: ErrorSeverity.CRITICAL,
    retryable: true,
    translationKey: 'DATABASE_ERROR',
    suggestedAction: 'RETRY',
  },
  UNKNOWN_ERROR: {
    code: 'UNKNOWN_ERROR',
    httpStatus: 500,
    severity: ErrorSeverity.ERROR,
    retryable: true,
    translationKey: 'UNKNOWN_ERROR',
    suggestedAction: 'RETRY',
  },
  INTERNAL_ERROR: {
    code: 'INTERNAL_ERROR',
    httpStatus: 500,
    severity: ErrorSeverity.CRITICAL,
    retryable: true,
    translationKey: 'INTERNAL_ERROR',
    suggestedAction: 'RETRY',
  },
  NETWORK_TIMEOUT: {
    code: 'NETWORK_TIMEOUT',
    httpStatus: 408,
    severity: ErrorSeverity.ERROR,
    retryable: true,
    translationKey: 'NETWORK_TIMEOUT',
    suggestedAction: 'RETRY',
  },
  NETWORK_DISCONNECTED: {
    code: 'NETWORK_DISCONNECTED',
    httpStatus: 0,
    severity: ErrorSeverity.ERROR,
    retryable: true,
    translationKey: 'NETWORK_DISCONNECTED',
    suggestedAction: 'RETRY',
  },
};
